### ISSUE TITLE
Readme should be improved to state the purpose of this repo

### ISSUE THREAD

**Issue by lextm** [alexsilva/wfastcgi#2]
The wfastcgi source code has been part of [Microsoft's own repo](https://github.com/Microsoft/PTVS/tree/main/Python/Product/WFastCgi) for years, not sure why you created this repo with the same contents.

If your goal is to continue the development of this Python script/package, you should describe clearly in the Readme file.

Optionally you might publish your own Python package (using a name like "wfastcgi-alexsilva"), so that people can discover/consume your work more easily.

**Comment by alexsilva** [comment]
It's not the same content [commits](https://github.com/alexsilva/wfastcgi/commits/master). And why do you care?

This script is not the best solution for serving web requests. It is better to work with a reverse proxy.

**Comment by lextm** [comment]
Unfortunately search engines right now put this repo in the top results for wfastcgi, so anyone landing here should be warned that this is Derivative Works, not the original.

**Comment by alexsilva** [comment]
@lextm [Warning for original code](https://github.com/alexsilva/wfastcgi/commit/dcfac45c74bf6f47a5442a1c4fb042f61bcc95d8)
I hope it's enough. Your point is valid.
